#!/bin/bash

# Create the Jupyter config directory if it doesn't exist
mkdir -p $HOME/.jupyter/

# Move the jupyter_notebook_config.py file to the correct location
mv $HOME/.binder/jupyter_notebook_config.py $HOME/.jupyter/

